<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-454JC8E" name="pytest" skipped="0" tests="2" time="0.023" timestamp="2019-12-18T10:45:33.772215"><testcase classname="Tests.test_body.Test_test_body" file="Tests\test_body.py" line="12" name="test_angle" time="0.000"></testcase><testcase classname="Tests.test_body.Test_test_body" file="Tests\test_body.py" line="7" name="test_simple" time="0.000"><failure message="AssertionError: &lt;Body.Body object at 0x000001C8DC69EB08&gt; != &lt;Body.Body object at 0x000001C8DC69EA48&gt;">self = &lt;test_body.Test_test_body testMethod=test_simple&gt;

    def test_simple(self):
        body = Body.simple()
    
&gt;       self.assertEqual(Body(Vector(0, 0), Vector(0, 0), 0, 0, False), body)
E       AssertionError: &lt;Body.Body object at 0x000001C8DC69EB08&gt; != &lt;Body.Body object at 0x000001C8DC69EA48&gt;

Tests\test_body.py:11: AssertionError</failure></testcase></testsuite></testsuites>